//
//  SEJob.h
//  sechi
//
//  Created by karolszafranski on 09.05.2014.
//  Copyright (c) 2014 TopCoder Inc. All rights reserved.
//

#import <Foundation/Foundation.h>
#import <CoreData/CoreData.h>


@interface SEJob : NSManagedObject

/**
 * Property for saving _c5_source field returned from API for job object.
 */
@property (nonatomic, retain) NSString * c5Source;

/**
 * Property for saving client_account__c field returned from API for job object.
 */
@property (nonatomic, retain) NSString * clientAccountC;

/**
 * Property for saving client_contact__c field returned from API for job object.
 */
@property (nonatomic, retain) NSString * clientContactC;

/**
 * Property for saving client_name__c field returned from API for job object.
 */
@property (nonatomic, retain) NSString * clientNameC;

/**
 * Property for saving contact_name__c field returned from API for job object.
 */
@property (nonatomic, retain) NSString * contactNameC;

/**
 * Property for saving createddate field returned from API for job object.
 */
@property (nonatomic, retain) NSDate * createdDate;

/**
 * Property for saving id field returned from API for job object.
 */
@property (nonatomic, retain) NSNumber * identifier;

/**
 * Property for saving info_text__c field returned from API for job object.
 */
@property (nonatomic, retain) NSString * infoTextC;

/**
 * Property for saving isdeleted field returned from API for job object.
 */
@property (nonatomic, retain) NSString * removed;

/**
 * Property for saving job_address__c field returned from API for job object.
 */
@property (nonatomic, retain) NSString * jobAddressC;

/**
 * Property for saving job_end_time__c field returned from API for job object.
 */
@property (nonatomic, retain) NSDate * jobEndTimeC;

/**
 * Property for saving job_name__c field returned from API for job object.
 */
@property (nonatomic, retain) NSString * jobNameC;

/**
 * Property for saving job_start_time__c field returned from API for job object.
 */
@property (nonatomic, retain) NSDate * jobStartTimeC;

/**
 * Property for saving lastmodifieddate field returned from API for job object.
 */
@property (nonatomic, retain) NSDate * lastModifiedDate;

/**
 * Property for saving latitude__c field returned from API for job object.
 */
@property (nonatomic, retain) NSNumber * latitudeC;

/**
 * Property for saving longitude__c field returned from API for job object.
 */
@property (nonatomic, retain) NSNumber * longitudeC;

/**
 * Property for saving name field returned from API for job object.
 */
@property (nonatomic, retain) NSString * name;

/**
 * Property for saving notes__c field returned from API for job object.
 */
@property (nonatomic, retain) NSString * notesC;

/**
 * Property for saving phone__c field returned from API for job object.
 */
@property (nonatomic, retain) NSString * phoneC;

/**
 * Property for saving sfid field returned from API for job object.
 */
@property (nonatomic, retain) NSString * sfid;

/**
 * Property for saving status__c field returned from API for job object.
 */
@property (nonatomic, retain) NSString * statusC;

/**
 * Property for saving job photos
 */
@property (nonatomic, retain) NSOrderedSet *photos;

@end

/**
 *  Methods generated by Xcode
 */
@interface SEJob (CoreDataGeneratedAccessors)

- (void)insertObject:(NSManagedObject *)value inPhotosAtIndex:(NSUInteger)idx;
- (void)removeObjectFromPhotosAtIndex:(NSUInteger)idx;
- (void)insertPhotos:(NSArray *)value atIndexes:(NSIndexSet *)indexes;
- (void)removePhotosAtIndexes:(NSIndexSet *)indexes;
- (void)replaceObjectInPhotosAtIndex:(NSUInteger)idx withObject:(NSManagedObject *)value;
- (void)replacePhotosAtIndexes:(NSIndexSet *)indexes withPhotos:(NSArray *)values;
- (void)addPhotosObject:(NSManagedObject *)value;
- (void)removePhotosObject:(NSManagedObject *)value;
- (void)addPhotos:(NSOrderedSet *)values;
- (void)removePhotos:(NSOrderedSet *)values;

/**
 *  Returns RestKit RKEntityMapping used for SEJob object in provided managed object store.
 *
 *  @param managedObjectStore managedObjectStore where objects will be stored
 *
 *  @return RKEntityMapping for use in RestKit response and request descriptors
 */
+ (RKEntityMapping*) responseMappingForManagedObjectStore: (RKManagedObjectStore*) managedObjectStore;

@end
